### ISSUE TITLE
"Error: Some file corrupted during upload" 出错概率太大

### ISSUE THREAD

**Issue by zensh** [teambition/cdn-uploader#2]
```
Error: Some file corrupted during upload
  at [object Object].<anonymous> (/Users/zensh/git/teambition/community/node_modules/cdn-uploader/index.js:112:23)
  at [object Object].g (events.js:260:16)
  at emitNone (events.js:72:20)
  at [object Object].emit (events.js:166:7)
  at endReadableNT (_stream_readable.js:913:12)
  at nextTickCallbackWith2Args (node.js:442:9)
  at process._tickCallback (node.js:356:17)
```

**Comment by nekolab** [comment]
OK I will investigate this issue

**Comment by Brooooooklyn** [comment]
@meowlab fix it please

**Comment by guan-wy** [comment]
@meowlab fix it please 
(´･Д･)」

**Comment by VeraWei** [comment]
@meowlab fix it now
(:--:)

**Comment by nekolab** [comment]
Hi everyone:
I'm happy to announce the new solution aiming to fix this issue, works on branch [vendor-slot](https://github.com/teambition/cdn-uploader/tree/feature/vendor-slot).

Reference commit: https://github.com/teambition/cdn-uploader/commit/86cc526115534bd0053549584b5ec3526c279aee

Feel free to review the code, write comment, let me know what you think about the new solution. Thanks for all your support.
